### ISSUE TITLE
Install file missing

### ISSUE THREAD

**Issue by Rulestormer** [darkoverlordofdata/bosco-player#1]
Can't follow your installation instructions, because the install file is missing.

Also, a noob question (my first time using GTK): tsc compiler keeps complaining that it can't find GTK module, whenever I try to import it. I have to manually edit the compiled js and add the "imports.gi.Gtk" line. (Doing it the JS way).
How do you properly do this in TypeScript?

**Comment by darkoverlordofdata** [comment]
oops - I tweaked the gitignore and pushed it back up. install is now included - Thanks!
So, importing gtk is not a 'true' import, it's just a variable assignment. So if you do it that way, it works, but typescript get's warning allover because then it doesn't recognize the 'import.gi' as a 'type'.
What I do is import it from JS,  and set the "allowJs": true in tsconfig.
it's buried dowin in src/gjs.js, which doubles as both my amd and gi loader.

**Comment by Rulestormer** [comment]
Thank you, it's working properly now.
